# Linear Algebra.jl

# Basic

* 줄리아에서는 기본적인 연산자들을 지원하며 그 예로 ```tr``` , ```det```, ```inv```, ```eigvals``` 등이 있다.

In [1]:
using Pkg
using LinearAlgebra

A = [ 1 2 3; 4 1 6; 7 8 1]

3×3 Matrix{Int64}:
 1  2  3
 4  1  6
 7  8  1

In [2]:
# 대각합(trace)

tr(A)

3

In [3]:
# 행렬식(determinant)

det(A)

104.0

In [4]:
# 역행렬(inverse matrix)
inv(A)

3×3 Matrix{Float64}:
 -0.451923   0.211538    0.0865385
  0.365385  -0.192308    0.0576923
  0.240385   0.0576923  -0.0673077

In [5]:
# 고유값 (eigen values)

A = [-4. -17.; 2. 2.]
eigvals(A)

2-element Vector{ComplexF64}:
 -1.0 - 5.0im
 -1.0 + 5.0im

In [6]:
# 고유벡터 (eigen values)
eigvecs(A)

2×2 Matrix{ComplexF64}:
  0.945905-0.0im        0.945905+0.0im
 -0.166924+0.278207im  -0.166924-0.278207im

**(행렬 분해)** 

* 줄리아는 다양한 행렬 분해법을 제공함으로써 선형 해법 또는 행렬 거듭제곱 등에서 빠른 속도를 지원하고 있다. 

In [7]:
A = [1.5 2 -4; 3 -1 -6; -10 2.3 4]

3×3 Matrix{Float64}:
   1.5   2.0  -4.0
   3.0  -1.0  -6.0
 -10.0   2.3   4.0

In [8]:
factorize(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0    0.0       0.0
 -0.15   1.0       0.0
 -0.3   -0.132196  1.0
U factor:
3×3 Matrix{Float64}:
 -10.0  2.3     4.0
   0.0  2.345  -3.4
   0.0  0.0    -5.24947

* 에르미트행렬(Hermitian), 대칭(symmetric), 삼각행렬(triangular), 3중 대각행렬(tridiagonal) 또는 이중 대각행렬(bidiagonal)이 아닌 경우 LU 분해가 최선의 factorization이 되므로 A에 대해서는 LU 분해가 자동으로 진행됨

* 위에 열거한 행렬들의 경우 적절한 분해(factorization) 방법이 적용되어 factorize 함수가 작동함

* 다음 예제는 3중 대각행렬인 B에 대해 BunchKaufman 분해법이 적용되는 모습을 나타냄

In [9]:
B = [1.5 2 -4; 2 -1 -3; -4 -3 5]

factorize(B)

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -1.64286   0.0   ⋅ 
  0.0      -2.8  0.0
   ⋅        0.0  5.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.142857  -0.8
  ⋅   1.0       -0.6
  ⋅    ⋅         1.0
permutation:
3-element Vector{Int64}:
 1
 2
 3

* 줄리아는 적절한 분해법이 적용될 수 있도록 행렬에 특별한 태그(데이터 구조 타입)을 설정할 수 있다.  

* 이렇게 적용된 행렬 구조 타입은 eigenfactorization or computing matrix-vector products와 같은 계산에 참조된다.

In [10]:
B = [1.5 2 -4; 2 -1 -3; -4 -3 5]

3×3 Matrix{Float64}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0  -3.0   5.0

In [11]:
# Symmetric matrix type tagging

sB = Symmetric(B)

3×3 Symmetric{Float64, Matrix{Float64}}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0  -3.0   5.0

**(선형해)**

* 그리고 줄리아는 ```\``` left-division operator를 제공함으로써 선형해를 찾는 방식을 간편하고 파워풀하게 제공하고 있다.



* 다음 같은 식에서 $\mathbf{x} = \left\{x_1, x_2, x_3\right\}$의 선형 해를 left-division operator ```\``` 를 이용해 쉽게 찾을 수 있다.

$$\begin{pmatrix}
1.5 & 2.0 & -4.0 \\
2.0 & -1.0 & -3.0 \\
-4.0 & -3.0 & 5.0 \\
\end{pmatrix}\begin{pmatrix}
x_1 \\
x_2 \\
x_3 \end{pmatrix} = \begin{pmatrix}
1 \\
2 \\
3 \end{pmatrix}$$

In [12]:
x = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [13]:
sB\x

3-element Vector{Float64}:
 -1.7391304347826084
 -1.1086956521739126
 -1.4565217391304346

* 구한 해가 맞는 지 검산을 하기 위해 sB와 해를 곱하면 x의 값이 나오는 것을 확인할 수 있다.

In [14]:
sol = sB\x

3-element Vector{Float64}:
 -1.7391304347826084
 -1.1086956521739126
 -1.4565217391304346

In [15]:
# 줄리아에서 행렬곱은 * 로 사용, numpy의 matmul 함수와 같음

sB*sol

3-element Vector{Float64}:
 1.0
 1.9999999999999996
 2.999999999999999