# Linear Algebra.jl

# Matrix Factorizations

## 1. Matrix factorizations

* 행렬 분해는 하나의 행렬을 두 개 이상의 행렬들의 행렬곱으로 계산하여 나타내는 것으로 선형대수학의 중심 개념 중 하나이다.

* 다음은 줄리아에서 지원하는 행렬 분해의 타입에 대해 요약한 표이다. 

|	Type 	|	Description	|	Standard Functions	|
|	:-----	|	:------------	|	:------------	|
|	**BunchKaufman**	|	Bunch-Kaufman factorization	|	```factorize```, ```BunchKaufman```, ```BunchKaufman!```	|
|	**Cholesky**	|	Cholesky factorization	|	```factorize```, ```Cholesky```, ```Cholesky!```	|
|	**CholeskyPivoted**	|	Pivoted Cholesky factorization	|	```factorize```, ```Cholesky```, ```Cholesky!```	|
|	**LDLt**	|	LDL(T) factorization	|	```factorize```, ```ldlt```, ```ldlt!```	|
|	**LU**	|	LU factorization	|	```factorize```, ```lu```, ```lu!```	|
|	**QR**	|	QR factorization	|	```factorize```, ```qr```, ```qr!```	|
|	**QRCompactWY**	|	Compact WY form of the QR factorization	|	```factorize```, ```qr```, ```qr!```	|
|	**QRPivoted**	|	Pivoted QR factorization	|	```factorize```, ```qr```, ```qr!```	|
|	**LQ**	|	QR factorization of transpose(A)	|	```lq```, ```lq!```	|
|	**Hessenberg**	|	Hessenberg decomposition	|	```Hessenberg```, ```Hessenberg!```	|
|	**Eigen**	|	Spectral decomposition	|	```eigen```, ```eigen!```, ```eigvals```, ```eigvals!```	|
|	**GeneralizedEigen**	|	Generalized spectral decomposition	|	```eigen```, ```eigen!```, ```eigvals```, ```eigvals!```	|
|	**SVD**	|	Singular Value Decomposition	|	```svd```, ```svd!```, ```svdvals```, ```svdvals!```	|
|	**GeneralizedSVD**	|	Generalized SVD	|	```svd```, ```svd!```, ```svdvals```, ```svdvals!```	|
|	**Schur**	|	Schur decomposition	|	```schur```, ```schur!```, ```ordschur```, ```ordschur!```	|
|	**GeneralizedSchur**	|	Generalized Schur decomposition	|	```schur```, ```schur!```, ```ordschur```, ```ordschur!```	|


## 2. Starndard functions of Matrix factorizations

### 2.1 factorize

* factorize 함수는 입력되는 행렬의 특정 형태(대칭/삼각 등)를 체크하고 적절한 분해법과 매치하여 결과값을 리턴하는 범용적 함수이다.

    - 예를 들어 입력되는 행렬이 에르미트 양정 행렬(Hermitian positive-definite matrix)이라면 촐레스키 분해 결과를 리턴한다.

    - 아래의 표는 입력되는 행렬의 특성에 따라 factorize 함수에서 적용되는 분해법에 대해 정리된 표이다. 

        + https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#man-linalg-factorizations
    

| Properties of A       | type of factorization                          |
|:---------------------------|:-----------------------------------------------|
| **Positive-definite**          | Cholesky   |
| **Dense Symmetric/Hermitian**  | Bunch-Kaufman  |
| **Sparse Symmetric/Hermitian** | LDLt     |
| **Triangular**                 | Triangular            |
| **Diagonal**                   | Diagonal          |
| **Bidiagonal**                 | Bidiagonal         |
| **Tridiagonal**                | LU   |
| **Symmetric real tridiagonal** | LDLt   |
| **General square**             | LU         |
| **General non-square**         | QR           |

* 리턴된 결과는 객체로 저장하여 다른 계산에도 활용 가능하며, 특정 행렬(special matrices) 타입에 맞게 반환하여 각 행렬 타입에 특화된 계산 방법에 적용 가능하도록 한다. 


In [1]:
# 예제 1) Bidiagonal 타입의 행렬이 입력될 경우

using LinearAlgebra

A = Array(Bidiagonal(fill(1.0, (5, 5)), :U))

5×5 Matrix{Float64}:
 1.0  1.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0
 0.0  0.0  1.0  1.0  0.0
 0.0  0.0  0.0  1.0  1.0
 0.0  0.0  0.0  0.0  1.0

In [2]:
# Bidiagonal factorization 결과를 리턴함

factorize(A)

5×5 Bidiagonal{Float64, Vector{Float64}}:
 1.0  1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0  1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0  1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0  1.0
  ⋅    ⋅    ⋅    ⋅   1.0

In [3]:
# 예제 2) 특정한 대칭구조를 가지지 않는 일반적인 정사각 행렬이 입력될 경우
A2 = [1.5 2 -4; 3 -1 -6; -10 2.3 4]
A2

3×3 Matrix{Float64}:
   1.5   2.0  -4.0
   3.0  -1.0  -6.0
 -10.0   2.3   4.0

In [4]:
# 이 경우 factorize 함수는 LU 분해의 결과를 리턴함
factorize(A2)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0    0.0       0.0
 -0.15   1.0       0.0
 -0.3   -0.132196  1.0
U factor:
3×3 Matrix{Float64}:
 -10.0  2.3     4.0
   0.0  2.345  -3.4
   0.0  0.0    -5.24947

In [5]:
# 예제 3) 대칭 행렬이 입력될 경우

A3 = [1.5 2 -4; 2 -1 -3; -4 -3 5]

3×3 Matrix{Float64}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0  -3.0   5.0

In [6]:
# 이 경우 BunchKaufman factorization 결과를 리턴함

factorize(A3)

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -1.64286   0.0   ⋅ 
  0.0      -2.8  0.0
   ⋅        0.0  5.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.142857  -0.8
  ⋅   1.0       -0.6
  ⋅    ⋅         1.0
permutation:
3-element Vector{Int64}:
 1
 2
 3

### 2.2 Cholesky

#### 2.2.1 Cholesky type and function

* 숄레스키 분해(Cholesky decomposition)는 에르미트 행렬(Hermitian matrix), 양의 정부호행렬(positive-definite matrix)의 분해에서 사용된다. 촐레스키 분해의 결과는 하삼각행렬과 하삼각행렬의 켤레전치 행렬의 곱으로 표현된다.

* 숄레스키 타입(Matrix factorization type of the Cholesky factorization)은 Factorization (Super Type)의 하위 자료형(sub type)이다. 

* 숄레스키 함수는 대칭 밀집행렬/양부호행렬(a dense symmetric/Hermitian positive definite matrix A)에 대한 숄레스키 타입을 반환하며, ```L```과 ```U``` 구성요소(attribute)로 분해하여 각 값을 반환한다. 

* 숄레스키 함수를 통해 산출된 숄레스키 객체는 ```size```, ```\```, ```inv```, ```det```, ```logdet```, ```isposdef``` 함수의 적용이 가능하다.

* 만약 check 인자(argument)를 ```check = true```로 입력하면, 분해 시 실패할 경우 에러가 발생. ```check = false```로 입력하면 분해의 유효성을 사용자에게 맡김

In [7]:
A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]

3×3 Matrix{Float64}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

In [8]:
C = cholesky(A)

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

In [9]:
C.U

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

In [10]:
C.L

3×3 LowerTriangular{Float64, Matrix{Float64}}:
  2.0   ⋅    ⋅ 
  6.0  1.0   ⋅ 
 -8.0  5.0  3.0

In [11]:
C.L * C.U == A

true

In [12]:
# 분해를 반복하여 구성요소 L과 U 도출
l, u = C; # destructuring via iteration

In [13]:
# 숄레스키 반환값과 객체값의 비교

l == C.L && u == C.U

true

#### 2.2.2 choleskyPivoted type and function

* 피벗된 숄레스키 분해 행렬의 타입이다. 

* 숄레스키 함수의 인자로 RowMaximum()을 입력함으로써 산출할 수 있다. ```cholesky(_, ::RowMaximum)```

* 삼각 숄레스키 함수는 ```F::CholeskyPivoted``` 분해를 통해 ```F.L```, ```F.U``` 및 ```F.p``` 를  얻을 수 있다. (분해를 반복하면 구성요소 ```L``` 과 ```U```를 구할 수 있음)

    * 확인 결과식은 다음과 같음

    * ```A[F.p, F.p] ≈ Ur' * Ur ≈ Lr * Lr'```
    
        - ```Ur = F.U[1:F.rank, :]``` ,  ```Lr = F.L[:, 1:F.rank] ```
        
    * ```A ≈ Up' * Up ≈ Lp * Lp' ```
        - ```Up = F.U[1:F.rank, invperm(F.p)]``` , ```Lp = F.L[invperm(F.p), 1:F.rank]```


* 피벗된 숄레스키 객체는  ```size``` , ```\``` , ```inv``` , ```det``` , ```rank``` 함수 적용이 가능하다.

* tol 인수는 순위를 결정하기 위한 허용 오차를 결정함. 음수 값의 경우 공차는 기계 정밀도임.

In [14]:
X = [1.0, 2.0, 3.0, 4.0]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [15]:
A = X * X'

4×4 Matrix{Float64}:
 1.0  2.0   3.0   4.0
 2.0  4.0   6.0   8.0
 3.0  6.0   9.0  12.0
 4.0  8.0  12.0  16.0

In [16]:
C = cholesky(A, RowMaximum(), check = false)

CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}
U factor with rank 1:
4×4 UpperTriangular{Float64, Matrix{Float64}}:
 4.0  2.0  3.0  1.0
  ⋅   0.0  6.0  2.0
  ⋅    ⋅   9.0  3.0
  ⋅    ⋅    ⋅   1.0
permutation:
4-element Vector{Int64}:
 4
 2
 3
 1

In [17]:
C.U[1:C.rank, :]' * C.U[1:C.rank, :] ≈ A[C.p, C.p]

true

In [18]:
C.U[1:C.rank, :]

1×4 Matrix{Float64}:
 4.0  2.0  3.0  1.0

In [19]:
A[C.p, C.p]

4×4 Matrix{Float64}:
 16.0  8.0  12.0  4.0
  8.0  4.0   6.0  2.0
 12.0  6.0   9.0  3.0
  4.0  2.0   3.0  1.0

In [20]:
# 반복을 통해 분해 행렬을 산출함
l, u = C; # destructuring via iteration

In [21]:
# 숄레스키 반환값과 객체값의 비교

l == C.L && u == C.U

true

#### 2.2.3 SparseMatrixCSC type

* 또한, 숄레스키 함수(cholesky)는 희소 정부호 행렬의 숄레스키 분해를 계산함

    * 입력되는 행렬은 대칭 이거나 에르미트 행렬의 희소 행렬이어야 함
    
    * _A must be a **```SparseMatrixCSC```** or a Symmetric/Hermitian view of a **```SparseMatrixCSC```**_
    
    * 입력 인자로 ```perm``` 이 주어지지 않을 경우  fill-reducing permutation이 사용된다.

* ```F = cholesky(A)``` 결과는 ```F\b``` 와 ```F``` 행렬에 대해 정의된 ```diag```, ```det```, ```logdet``` 방법도 사용한다.

* 기본 피벗으로 지정될 경우, 내부적으로 순열행렬(permutation matrix ```P```)을 이용하여 ```A == P'*L*L'*P```로 표현되므로 순열행렬 ```P```가 주어지지 않으면 올바르지 않은 답이 나온다.

    - 일반적으로 결합항(combined factors)을 추출하는 것이 선호됨
    
        - ```PtL = F.Pt``` (the equivalent of ```P'*L```)
        
        - ```LtP = F.UP``` (the equivalent of ```L'*P```)

* 아래는 fill-reducing permutation이 사용된 예제를 나타낸다.

In [22]:
# the fill-reducing permutation [3, 2, 1] 이 사용된 예제

A = [2 1 1; 1 2 0; 1 0 2]

3×3 Matrix{Int64}:
 2  1  1
 1  2  0
 1  0  2

In [23]:
using SparseArrays

C = cholesky(sparse(A))

SuiteSparse.CHOLMOD.Factor{Float64}
type:    LLt
method:  simplicial
maxnnz:  5
nnz:     5
success: true


In [24]:
C.p

3-element Vector{Int64}:
 3
 2
 1

In [25]:
L = sparse(C.L)

3×3 SparseMatrixCSC{Float64, Int64} with 5 stored entries:
 1.41421    ⋅         ⋅ 
  ⋅        1.41421    ⋅ 
 0.707107  0.707107  1.0

In [26]:
L * L' ≈ A[C.p, C.p]

true

In [27]:
A[C.p, C.p]

3×3 Matrix{Int64}:
 2  0  1
 0  2  1
 1  1  2

In [28]:
P = sparse(1:3, C.p, ones(3))

3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
  ⋅    ⋅   1.0
  ⋅   1.0   ⋅ 
 1.0   ⋅    ⋅ 

In [29]:
P' * L * L' * P ≈ A

true

```A == P'*L*L'*P```

In [30]:
P' * L * L' * P

3×3 SparseMatrixCSC{Float64, Int64} with 7 stored entries:
 2.0  1.0  1.0
 1.0  2.0   ⋅ 
 1.0   ⋅   2.0

In [31]:
C.p

3-element Vector{Int64}:
 3
 2
 1

In [32]:
C = cholesky(sparse(A), perm=1:3)

SuiteSparse.CHOLMOD.Factor{Float64}
type:    LLt
method:  simplicial
maxnnz:  6
nnz:     6
success: true


In [33]:
C.p

3-element Vector{Int64}:
 1
 2
 3

In [34]:
L = sparse(C.L)

3×3 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 1.41421     ⋅         ⋅ 
 0.707107   1.22474    ⋅ 
 0.707107  -0.408248  1.1547

In [35]:
Matrix(L)

3×3 Matrix{Float64}:
 1.41421    0.0       0.0
 0.707107   1.22474   0.0
 0.707107  -0.408248  1.1547

In [36]:
L * L' ≈ A

true

In [37]:
L * L'

3×3 SparseMatrixCSC{Float64, Int64} with 9 stored entries:
 2.0  1.0  1.0
 1.0  2.0  0.0
 1.0  0.0  2.0

### 2.3 BunchKaufman

* BunchKaufman 함수는 대칭 및 에르미트 행렬 A에 대해 ```P'*U*D*U'*P``` 또는 ```P'*L*D*L'*P``` 로 분해하는 함수이다. 결과값은 BunchKaufman 객체이며, 입력 함수 A의 삼각행렬에 의존한다.

* A가 복소 대칭 행렬일 경우, ```U'```, ```L'```은 비켤레 전치(unconjugated transposes) 

* 만약 check 인자(argument)를 ```check = true```로 입력하면, 분해 시 실패할 경우 에러가 발생. ```check = false```로 입력하면 분해의 유효성을 사용자에게 맡김

In [38]:
A = [1 2; 2 3]

2×2 Matrix{Int64}:
 1  2
 2  3

In [39]:
# 예제 1) A에 대해 BunchKaufman 함수 적용(upper triangular matrix 이용)

# 입력 행렬이 일반 행렬이더라도 함수 내부에서 symmetric 타입으로 변환됨
# A gets wrapped internally by Symmetric(A)

S = bunchkaufman(A) 

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
2×2 Tridiagonal{Float64, Vector{Float64}}:
 -0.333333  0.0
  0.0       3.0
U factor:
2×2 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.666667
  ⋅   1.0
permutation:
2-element Vector{Int64}:
 1
 2

In [40]:
Symmetric(A)

2×2 Symmetric{Int64, Matrix{Int64}}:
 1  2
 2  3

In [41]:
d, u, p = S; # destructuring via iteration

In [42]:
d

2×2 Tridiagonal{Float64, Vector{Float64}}:
 -0.333333  0.0
  0.0       3.0

In [43]:
u

2×2 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.666667
  ⋅   1.0

In [44]:
p

2-element Vector{Int64}:
 1
 2

In [45]:
# 리턴값과 객체 내 속성값 동일 여부 비교
d == S.D && u == S.U && p == S.p

true

In [46]:
S.U*S.D*S.U' - S.P*A*S.P'

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [47]:
S.U*S.D*S.U' - A[S.p, S.p]

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [48]:
A[S.p, S.p]

2×2 Matrix{Int64}:
 1  2
 2  3

In [49]:
S.P*A*S.P'

2×2 Matrix{Float64}:
 1.0  2.0
 2.0  3.0

In [50]:
S.U*S.D*S.U'

2×2 Matrix{Float64}:
 1.0  2.0
 2.0  3.0

In [51]:
# 예제 2) Lower triangular matrix 이용 

S = bunchkaufman(Symmetric(A, :L))

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
2×2 Tridiagonal{Float64, Vector{Float64}}:
 3.0   0.0
 0.0  -0.333333
L factor:
2×2 UnitLowerTriangular{Float64, Matrix{Float64}}:
 1.0        ⋅ 
 0.666667  1.0
permutation:
2-element Vector{Int64}:
 2
 1

In [52]:
Symmetric(A, :L)

2×2 Symmetric{Int64, Matrix{Int64}}:
 1  2
 2  3

In [53]:
S.L*S.D*S.L' - A[S.p, S.p]

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [54]:
A[S.p, S.p]

2×2 Matrix{Int64}:
 3  2
 2  1

In [55]:
S.L*S.D*S.L'

2×2 Matrix{Float64}:
 3.0  2.0
 2.0  1.0

### 2.4 ldlt

* ldlt 함수는 S가 실수로 이루어진 대칭 삼중 대각 행렬(SymTridiagoanl)일 때, ```S = L*Diagonal(d)*L'```로 분해하는 함수

* ```L```은 단위하삼각행렬(unit lower triangular matrix) 이며, ```d```는 벡터이다. 

* ```F = ldlt(S)```의 주요 사용 용도는 Matrix division operator(left-division operator) ```'\'``` 를 이용한 ```Sx = b``` 에 대한 선형 해를 풀 때 사용된다.

* ldlt 함수가 반환하는 LDLt 타입의 객체는 F.L 또는 getproperty(ldltS, :L)로 그 속성(attr)을 찾을 수 있다.


|Component | Description |
|:---------|:------------|
|```F.L``` |```L``` (unit lower triangular) part of ```LDLt``` |
|```F.D``` |```D``` (diagonal) part of ```LDLt``` |
|```F.Lt```|```Lt``` (unit upper triangular) part of ```LDLt``` |
|```F.d```|diagonal values of ```D``` as a ```Vector``` |


* sparse matrix도 지원하는데, 이때 인수로 입력되는 행렬은 **SparseMatrixCSC** 또는 **대칭/에르미트 SparseMatrixCSC** 여야 한다.

In [56]:
S = SymTridiagonal([3., 4., 5.], [1., 2.])

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 3.0  1.0   ⋅ 
 1.0  4.0  2.0
  ⋅   2.0  5.0

In [57]:
ldltS = ldlt(S)

LDLt{Float64, SymTridiagonal{Float64, Vector{Float64}}}
L factor:
3×3 UnitLowerTriangular{Float64, SymTridiagonal{Float64, Vector{Float64}}}:
 1.0        ⋅         ⋅ 
 0.333333  1.0        ⋅ 
 0.0       0.545455  1.0
D factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 3.0   ⋅        ⋅ 
  ⋅   3.66667   ⋅ 
  ⋅    ⋅       3.90909

In [58]:
getproperty(ldltS, :L)

3×3 UnitLowerTriangular{Float64, SymTridiagonal{Float64, Vector{Float64}}}:
 1.0        ⋅         ⋅ 
 0.333333  1.0        ⋅ 
 0.0       0.545455  1.0

In [59]:
b = [6., 7., 8.]

3-element Vector{Float64}:
 6.0
 7.0
 8.0

In [60]:
ldltS \ b

3-element Vector{Float64}:
 1.7906976744186047
 0.627906976744186
 1.3488372093023255

In [61]:
S \ b

3-element Vector{Float64}:
 1.7906976744186047
 0.627906976744186
 1.3488372093023255

In [62]:
S = SymTridiagonal([3., 4., 5.], [1., 2.])

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 3.0  1.0   ⋅ 
 1.0  4.0  2.0
  ⋅   2.0  5.0

**ldlt!**

입력되는 인수에 오버라이팅 되는 ldlt 함수

In [63]:
ldltS2 = ldlt!(S)

LDLt{Float64, SymTridiagonal{Float64, Vector{Float64}}}
L factor:
3×3 UnitLowerTriangular{Float64, SymTridiagonal{Float64, Vector{Float64}}}:
 1.0        ⋅         ⋅ 
 0.333333  1.0        ⋅ 
 0.0       0.545455  1.0
D factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 3.0   ⋅        ⋅ 
  ⋅   3.66667   ⋅ 
  ⋅    ⋅       3.90909

In [64]:
ldltS2

LDLt{Float64, SymTridiagonal{Float64, Vector{Float64}}}
L factor:
3×3 UnitLowerTriangular{Float64, SymTridiagonal{Float64, Vector{Float64}}}:
 1.0        ⋅         ⋅ 
 0.333333  1.0        ⋅ 
 0.0       0.545455  1.0
D factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 3.0   ⋅        ⋅ 
  ⋅   3.66667   ⋅ 
  ⋅    ⋅       3.90909

In [65]:
S

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 3.0       0.333333   ⋅ 
 0.333333  3.66667   0.545455
  ⋅        0.545455  3.90909

In [66]:
ldltS2 === S

false

In [67]:
ldlt!(S)

LDLt{Float64, SymTridiagonal{Float64, Vector{Float64}}}
L factor:
3×3 UnitLowerTriangular{Float64, SymTridiagonal{Float64, Vector{Float64}}}:
 1.0        ⋅         ⋅ 
 0.111111  1.0        ⋅ 
 0.0       0.150278  1.0
D factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 3.0   ⋅        ⋅ 
  ⋅   3.62963   ⋅ 
  ⋅    ⋅       3.82712

### 2.5 lu

* 많은 이들에게 친숙한 상삼각행렬과 하삼각행렬로 분해하는 LU분해 **```A = LU```** 를 지원하는 함수이다. 

*  lu함수는 lu 타입의 객체를 반환하는데 ```lu(A, pivot = RowMaximum(); check = true) -> F::LU{T,S{T}}``` 이때, lu함수로부터 도출되는 필드 속성은 다음과 같다.

|	Component	|	Description
|	:-----:	|	:-----:
|	F.L	|	L (unit lower triangular) part of LU
|	F.U	|	U (upper triangular) part of LU
|	F.p	|	(right) permutation Vector
|	F.P	|	(right) permutation Matrix


* lu 결과에 적용할 수 있는 기본 행렬 연산 함수는 다음과 같다. 

|	Component	|LU|LU{T,Tridiagonal{T}}|
|	:-----	|	:-----: |	:-----: |
|/          |✓          |           |
|\          |✓          |          ✓|
|inv|✓|✓|
|det|✓|✓|
|logdet|✓|✓|
|logabsdet|✓|✓|
|size|✓|✓|

* lu 함수에 실수 및 복소수 형태의 희소 행렬(sparse matrix)을 입력하면, 반환값 F는 ```UmfpackLU{Tv, Ti}``` 형태로 반환되며 Tv = Float64 or ComplexF64 이며 Ti는 정수형태 Int32 또는 Int64 타입으로 반환된다. F의 속성(필드)은 다음과 같다.

|Component|Description
|:-----:|:-----:
|L|L (lower triangular) part of LU
|U|U (upper triangular) part of LU
|p| right permutation Vector
|q| left permutation Vector
|Rs| Vector of scaling factors
|:| (L,U,p,q,Rs) components


In [68]:
# input 행렬 설정

A = [4 3; 6 3]

2×2 Matrix{Int64}:
 4  3
 6  3

In [69]:
F = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
2×2 Matrix{Float64}:
 1.0       0.0
 0.666667  1.0
U factor:
2×2 Matrix{Float64}:
 6.0  3.0
 0.0  1.0

In [70]:
A[F.p, :]

2×2 Matrix{Int64}:
 6  3
 4  3

In [71]:
F.L * F.U == A[F.p, :]

true

In [72]:
F.L * F.U

2×2 Matrix{Float64}:
 6.0  3.0
 4.0  3.0

In [73]:
A[F.p, :]

2×2 Matrix{Int64}:
 6  3
 4  3

In [74]:
F.p

2-element Vector{Int64}:
 2
 1

In [75]:
l, u, p = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
2×2 Matrix{Float64}:
 1.0       0.0
 0.666667  1.0
U factor:
2×2 Matrix{Float64}:
 6.0  3.0
 0.0  1.0

In [76]:
l == F.L && u == F.U && p == F.p

true

In [77]:
l

2×2 Matrix{Float64}:
 1.0       0.0
 0.666667  1.0

In [78]:
u

2×2 Matrix{Float64}:
 6.0  3.0
 0.0  1.0

In [79]:
p

2-element Vector{Int64}:
 2
 1

### 2.6 qr

* QR 분해는 A = QR 형태로 행렬을 분해하는 것으로 여기서 Q는 정규직교(orthogonal) 또는 unitary matrix이며 R은 상삼각행렬(upper triangular matrix)이다. 

$$ A = QR $$

$$Q = \prod_{i=1}^{\min(m,n)} (I - \tau_i v_i v_i^T)$$

* QR 분해 결과로 도출되는 객체 F ```qr(A, pivot = NoPivot(); blocksize) -> F``` 는 다음의 속성을 가지고 있다. 

    * 여기서 pivot == ColumnNorm()으로 인수를 입력하면 도출되는 객체 F는 QRPivoted 객체이다.

|	Component	|	Description
|	:-----:	|	:-----:
|F.Q	|	the orthogonal/unitary matrix Q
|F.R	|	the upper triangular matrix R
|F.p	|	the permutation vector of the pivot (QRPivoted only)
|F.P	|	the permutation matrix of the pivot (QRPivoted only)

* QR 분해 결과 도출되는 객체는 ```inv```, ```size```, ```\``` 적용이 가능하다. 여기서 A가 직사각형의 형태라면 ```\```는 최소자승해(least square solution)를 반환한다. 다만, 반환되는 해는 고유한 값이 아닌 가장 작은 norm 값이 반환된다.

* qr 함수는 희소 행렬 (sparseMatrixCSC를 입력받을 수 있으며, ```F.R = F.Q'*A[F.prow,F.pcol]```와 같이 fill-reducing row와 column permutations를 이용하여 나타낼 수 있다. 


In [80]:
A = [3.0 -6.0; 4.0 -8.0; 0.0 1.0]

3×2 Matrix{Float64}:
 3.0  -6.0
 4.0  -8.0
 0.0   1.0

In [81]:
F = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.6   0.0   0.8
 -0.8   0.0  -0.6
  0.0  -1.0   0.0
R factor:
2×2 Matrix{Float64}:
 -5.0  10.0
  0.0  -1.0

In [82]:
F.Q * F.R == A

true

In [83]:
# QR sparse

A = sparse([1,2,3,4], [1,1,2,2], [1.0,1.0,1.0,1.0])

4×2 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅ 
 1.0   ⋅ 
  ⋅   1.0
  ⋅   1.0

In [84]:
qr(A)

SuiteSparse.SPQR.QRSparse{Float64, Int64}
Q factor:
4×4 SuiteSparse.SPQR.QRSparseQ{Float64, Int64}:
 -0.707107   0.0        0.0       -0.707107
  0.0       -0.707107  -0.707107   0.0
  0.0       -0.707107   0.707107   0.0
 -0.707107   0.0        0.0        0.707107
R factor:
2×2 SparseMatrixCSC{Float64, Int64} with 2 stored entries:
 -1.41421    ⋅ 
   ⋅       -1.41421
Row permutation:
4-element Vector{Int64}:
 1
 3
 4
 2
Column permutation:
2-element Vector{Int64}:
 1
 2

In [85]:
# qr!
a = [1. 2.; 3. 4.]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [86]:
qr!(a)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
2×2 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.316228  -0.948683
 -0.948683   0.316228
R factor:
2×2 Matrix{Float64}:
 -3.16228  -4.42719
  0.0      -0.632456

In [87]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [88]:
qr!(a) # 입력값이 integer type 인 경우 출력값이 float이므로 !함수가 내용 인자를 치환하고자 한다면 에러가 발생항

LoadError: InexactError: Int64(3.1622776601683795)

### 2.7 lq

**type**

* LQ 분해는 A의 전치 행렬에 대한 QR 분해로 하삼각행렬(the lower triangular component) L과 정규직교(orthogonal)/unitary 행렬로 분해된다. 

$$A ≈ S.L*S.Q$$

**function**

* lq 함수는 LQ 분해를 수행하는 함수로 minimum-norm solution ```lq(A) \ b```를 구하는데 유용하다.


In [89]:
A = [5. 7.; -2. -4.]

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [90]:
S = lq(A)

LQ{Float64, Matrix{Float64}, Vector{Float64}}
L factor:
2×2 Matrix{Float64}:
 -8.60233   0.0
  4.41741  -0.697486
Q factor:
2×2 LinearAlgebra.LQPackedQ{Float64, Matrix{Float64}, Vector{Float64}}:
 -0.581238  -0.813733
 -0.813733   0.581238

In [91]:
S.L * S.Q

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [92]:
l, q = S

LQ{Float64, Matrix{Float64}, Vector{Float64}}
L factor:
2×2 Matrix{Float64}:
 -8.60233   0.0
  4.41741  -0.697486
Q factor:
2×2 LinearAlgebra.LQPackedQ{Float64, Matrix{Float64}, Vector{Float64}}:
 -0.581238  -0.813733
 -0.813733   0.581238

In [93]:
l == S.L &&  q == S.Q

true

### 2.8 Hessenberg

* 헤센베르그 분해는 A = QHQ'로 분해하는 분해법으로 인수가 되는 행렬 A는 에르미트 또는 실수로 구성된 대칭 행렬이다. 

    - 헤센베르스 분해를 통해 도출되는 객체 F의 F.Q는 실수로 구성된 대칭 삼각행렬이고 F.H는 대칭 삼각대각 행렬(SymTridiagonal)이 된다. 


* shifted factorization이 일어나면 ```A+μI = Q (H+μI) Q'``` UnifomScaling 객체 I를 사용하여 ```F + μ*I```로 효과적으로 구성할 수 있다. 이때 shift된 ```F```는 ```F.μ```의 필드(속성)을 가지게 되며 ```(F + μ*I) \ b```에 대한 해를 구하는데 사용된다.

In [94]:
A = [4. 9. 7.; 4. 4. 1.; 4. 3. 2.]

3×3 Matrix{Float64}:
 4.0  9.0  7.0
 4.0  4.0  1.0
 4.0  3.0  2.0

In [95]:
F = hessenberg(A)

Hessenberg{Float64, UpperHessenberg{Float64, Matrix{Float64}}, Matrix{Float64}, Vector{Float64}, Bool}
Q factor:
3×3 LinearAlgebra.HessenbergQ{Float64, Matrix{Float64}, Vector{Float64}, false}:
 1.0   0.0        0.0
 0.0  -0.707107  -0.707107
 0.0  -0.707107   0.707107
H factor:
3×3 UpperHessenberg{Float64, Matrix{Float64}}:
  4.0      -11.3137       -1.41421
 -5.65685    5.0           2.0
   ⋅        -8.88178e-16   1.0

In [96]:
F.Q * F.H * F.Q'

3×3 Matrix{Float64}:
 4.0  9.0  7.0
 4.0  4.0  1.0
 4.0  3.0  2.0

In [97]:
q, h = F

Hessenberg{Float64, UpperHessenberg{Float64, Matrix{Float64}}, Matrix{Float64}, Vector{Float64}, Bool}
Q factor:
3×3 LinearAlgebra.HessenbergQ{Float64, Matrix{Float64}, Vector{Float64}, false}:
 1.0   0.0        0.0
 0.0  -0.707107  -0.707107
 0.0  -0.707107   0.707107
H factor:
3×3 UpperHessenberg{Float64, Matrix{Float64}}:
  4.0      -11.3137       -1.41421
 -5.65685    5.0           2.0
   ⋅        -8.88178e-16   1.0

In [98]:
q == F.Q && h == F.H

true

### 2.9 Eigen

**type**

* 행렬 분해 함수에서 사용되는 고유값과 고유벡터에 대한 데이터 타입으로 Eigen type 생성

* 만약 F 객체가 Eigen 타입이라면 고유값은 ```F.values```, 고유 벡터(행렬의 컬럼)는 ```F.vectors```로 구할 수 있다.

    - k 번재 고유벡터는 F.vectors[:, k]로 구할 수 있다. 

In [99]:
[1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0]

3×3 Matrix{Float64}:
 1.0  0.0   0.0
 0.0  3.0   0.0
 0.0  0.0  18.0

In [100]:
F = eigen([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
  1.0
  3.0
 18.0
vectors:
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [101]:
# 고유값 산출

F.values

3-element Vector{Float64}:
  1.0
  3.0
 18.0

In [102]:
# 고유 벡터 산출

F.vectors

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [103]:
vals, vecs = F

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
  1.0
  3.0
 18.0
vectors:
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [104]:
vals == F

false

In [105]:
vals == F.values

true

In [106]:
vals == F.values && vecs == F.vectors

true

**GeneralizedEigen type**

* 두 행렬을 인자로 받아서 일반화된 고유값과 고유벡터을 반환하는 타입

* F::GeneralizedEigen 타입 객체는 F::Eigen 객체와 필드는 동일


In [107]:
A = [1 0; 0 -1]

2×2 Matrix{Int64}:
 1   0
 0  -1

In [108]:
B = [0 1; 1 0]

2×2 Matrix{Int64}:
 0  1
 1  0

In [109]:
F = eigen(A, B)

GeneralizedEigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im
vectors:
2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

In [110]:
F.values

2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im

In [111]:
F.vectors

2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

In [112]:
vals, vecs = F

GeneralizedEigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im
vectors:
2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

In [113]:
vals == F.values && vecs == F.vectors

true

#### 2.9.1 eigvals

* 고유값(eigenvalues)을 반환하는 함수

In [114]:
# eigvals(A; permute::Bool=true, scale::Bool=true, sortby) -> values
diag_matrix = [1 0; 0 4]

2×2 Matrix{Int64}:
 1  0
 0  4

In [115]:
eigvals(diag_matrix)

2-element Vector{Float64}:
 1.0
 4.0

In [116]:
# scala input
eigvals(-2)

-2

In [117]:
# eigvals(A, B) -> values

A = [1 0; 0 -1]
B = [0 1; 1 0]
eigvals(A,B)

2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im

In [118]:
# eigvals(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> values
A = SymTridiagonal([1.; 2.; 1.], [2.; 3.])

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 1.0  2.0   ⋅ 
 2.0  2.0  3.0
  ⋅   3.0  1.0

In [119]:
eigvals(A, 2:2)

1-element Vector{Float64}:
 0.9999999999999996

In [120]:
eigvals(A)

3-element Vector{Float64}:
 -2.1400549446402604
  1.0000000000000002
  5.140054944640259

In [121]:
# eigvals(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> values
A = SymTridiagonal([1.; 2.; 1.], [2.; 3.])

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 1.0  2.0   ⋅ 
 2.0  2.0  3.0
  ⋅   3.0  1.0

In [122]:
eigvals(A, -1, 2)

1-element Vector{Float64}:
 1.0000000000000009

In [123]:
eigvals(A)

3-element Vector{Float64}:
 -2.1400549446402604
  1.0000000000000002
  5.140054944640259

**eigvals!**

In [124]:
# eigvals!(A; permute::Bool=true, scale::Bool=true, sortby) -> values
A = [1. 2.; 3. 4.]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [125]:
eigvals!(A)

2-element Vector{Float64}:
 -0.3722813232690143
  5.372281323269014

In [126]:
# The input matrix A will not contain its eigenvalues after eigvals! is called on it - A is used as a workspace.

A

2×2 Matrix{Float64}:
 -0.372281  -1.0
  0.0        5.37228

In [127]:
# eigvals!(A, B; sortby) -> values
A = [1. 0.; 0. -1.]

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [128]:
B = [0. 1.; 1. 0.]

2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0

In [129]:
eigvals!(A, B)

2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im

In [130]:
A

2×2 Matrix{Float64}:
 -0.0  -1.0
  1.0  -0.0

In [131]:
B

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

#### 2.9.2 eigmax

* eigenvalues 중 최대값 산출하는 함수

In [132]:
# eigmax(A; permute::Bool=true, scale::Bool=true)
A = [0 im; -im 0]

2×2 Matrix{Complex{Int64}}:
 0+0im  0+1im
 0-1im  0+0im

In [133]:
eigvals(A)

2-element Vector{Float64}:
 -1.0
  1.0

In [134]:
eigmax(A)

1.0

In [135]:
A = [0 im; -1 0]

2×2 Matrix{Complex{Int64}}:
  0+0im  0+1im
 -1+0im  0+0im

In [136]:
# A가 복소수 (허수부 또는 실수부로 분리되지 않고 혼재된 복소수)일 경우 에러 발생

eigmax(A) 

LoadError: DomainError with Complex{Int64}[0+0im 0+1im; -1+0im 0+0im]:
`A` cannot have complex eigenvalues.

In [137]:
# Note that if the eigenvalues of A are complex, this method will fail, since complex numbers cannot be sorted.
eigmax(A)

LoadError: DomainError with Complex{Int64}[0+0im 0+1im; -1+0im 0+0im]:
`A` cannot have complex eigenvalues.

#### 2.9.3 eigmin

* 가장 작은 고유값을 반환하는 함수

In [138]:
# eigmin(A; permute::Bool=true, scale::Bool=true)
A = [0 im; -im 0]

2×2 Matrix{Complex{Int64}}:
 0+0im  0+1im
 0-1im  0+0im

In [139]:
eigmin(A)

-1.0

In [140]:
A = [0 im; -1 0]

2×2 Matrix{Complex{Int64}}:
  0+0im  0+1im
 -1+0im  0+0im

In [141]:
# Note that if the eigenvalues of A are complex, this method will fail, since complex numbers cannot be sorted.

eigmin(A)

LoadError: DomainError with Complex{Int64}[0+0im 0+1im; -1+0im 0+0im]:
`A` cannot have complex eigenvalues.

#### 2.9.4 eigvecs

* A의 고유벡터들로 이루어진 행렬 M을 반환

    - k 번재 고유 벡터를 얻고자 한다면 행렬 M에 대해 slicing 실시: ```M[:, k]```

In [142]:
# eigvecs(A::SymTridiagonal[, eigvals]) -> Matrix

A = SymTridiagonal([1.; 2.; 1.], [2.; 3.])

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 1.0  2.0   ⋅ 
 2.0  2.0  3.0
  ⋅   3.0  1.0

In [143]:
eigvals(A)

3-element Vector{Float64}:
 -2.1400549446402604
  1.0000000000000002
  5.140054944640259

In [144]:
eigvecs(A)

3×3 Matrix{Float64}:
  0.418304  -0.83205      0.364299
 -0.656749  -7.39009e-16  0.754109
  0.627457   0.5547       0.546448

In [145]:
eigvecs(A, [1.])

3×1 Matrix{Float64}:
  0.8320502943378436
  4.2635141280923656e-17
 -0.554700196225229

In [146]:
# eigvecs(A; permute::Bool=true, scale::Bool=true, `sortby`) -> Matrix

eigvecs([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [147]:
# eigvecs(A, B) -> Matrix

A = [1 0; 0 -1]

2×2 Matrix{Int64}:
 1   0
 0  -1

In [148]:
B = [0 1; 1 0]

2×2 Matrix{Int64}:
 0  1
 1  0

In [149]:
# generalized eigenvector

eigvecs(A, B)

2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

#### 2.9.5 eigen function

* 앞서 언급한 바와 같이 Eigen 타입을 만드는 함수로 Eigen 타입의 객체는 Eigenvalues와 Eigenvectors를 필드(속성)으로 가지고 있음

* 이러한 eigen 객체에는 ```inv``` , ```det``` , ```isposdef``` 함수의 적용이 가능하다.

* 일반적인 비대칭 행렬의 경우 고유 벡터를 계산하기 위한 인자(옵션)를 조정할 수 있다. permute=true 옵션은 행렬이 삼각형 상부에 가까워지도록 허용하고, scale=true는 행렬의 대각선 요소를 기준으로 scale을 조정하여 행과 열을 norm과 더 동일하게 만듭니다. 두 옵션 모두에 대해 기본값은 true로 설정되어 있다.

* 고유값과 고유벡터들은 ```(real(λ),imag(λ))```에 따라 사전편찬적(lexicographically)으로 정렬되어 있다. ```sortby=nothing``` 으로 지정하면 임의적인 순서(order)로 정렬된다. (다만 대각행렬(Diagonal)이나 대칭 삼중 대각행렬(SymTridiagonal)의 경우 sortby를 인수로 받지 않는다.)

In [150]:
# eigen(A; permute::Bool=true, scale::Bool=true, sortby) -> Eigen
F = eigen([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
  1.0
  3.0
 18.0
vectors:
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [151]:
F.values

3-element Vector{Float64}:
  1.0
  3.0
 18.0

In [152]:
F.vectors

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [153]:
vals, vecs = F

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
  1.0
  3.0
 18.0
vectors:
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [154]:
vals == F.values && vecs == F.vectors

true

In [155]:
# eigen(A, B; sortby) -> GeneralizedEigen
A = [1 0; 0 -1]

2×2 Matrix{Int64}:
 1   0
 0  -1

In [156]:
B = [0 1; 1 0]

2×2 Matrix{Int64}:
 0  1
 1  0

In [157]:
# eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> Eigen

# eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> Eigen

**GeneralizedEigen**

* eigen 함수는 두 개의 행렬을 인수로 받을 경우, GeneralizedEigen 타입을 반환함

In [158]:
F = eigen(A, B)

GeneralizedEigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im
vectors:
2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

In [159]:
F.values

2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im

In [160]:
F.vectors

2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

In [161]:
vals, vecs = F

GeneralizedEigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im
vectors:
2×2 Matrix{ComplexF64}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

In [162]:
vals == F.values && vecs == F.vectors

true

In [163]:
# eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> Eigen

# eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> Eigen

**eigen!**

```julia
eigen!(A; permute, scale, sortby)

eigen!(A, B; sortby)
```
eigen 함수와 동일하지만 복사본을 만드는 대신 입력 인수에 오버래핑하여 메모리 공간을 절약함

### 2.10 svd

#### 2.10.1 SVD and generalizedSVD

**type**

SVD <: Factorization


* SVD 타입은 특이값 분해의 행렬 분해 타입이다. 

    * 만약 SVD 타입 객체로 ```F::SVD``` 생성된다면 ```A = U * Diagonal(S) * Vt```의 결과는 ```F.U```, ```F.S```, ```F.V```, ```F.Vt```로 도출할 수 있다. 

    * ```S```의 특이값은 **내림차순** 으로 정렬된다.


In [164]:
A = [1. 0. 0. 0. 2.; 0. 0. 3. 0. 0.; 0. 0. 0. 0. 0.; 0. 2. 0. 0. 0.]

4×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  2.0
 0.0  0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0  0.0

In [165]:
F = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×4 Matrix{Float64}:
 0.0  1.0  0.0   0.0
 1.0  0.0  0.0   0.0
 0.0  0.0  0.0  -1.0
 0.0  0.0  1.0   0.0
singular values:
4-element Vector{Float64}:
 3.0
 2.23606797749979
 2.0
 0.0
Vt factor:
4×5 Matrix{Float64}:
 -0.0       0.0  1.0  -0.0  0.0
  0.447214  0.0  0.0   0.0  0.894427
 -0.0       1.0  0.0  -0.0  0.0
  0.0       0.0  0.0   1.0  0.0

In [166]:
F.U * Diagonal(F.S) * F.Vt

4×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  2.0
 0.0  0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0  0.0

In [167]:
u, s, v = F

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×4 Matrix{Float64}:
 0.0  1.0  0.0   0.0
 1.0  0.0  0.0   0.0
 0.0  0.0  0.0  -1.0
 0.0  0.0  1.0   0.0
singular values:
4-element Vector{Float64}:
 3.0
 2.23606797749979
 2.0
 0.0
Vt factor:
4×5 Matrix{Float64}:
 -0.0       0.0  1.0  -0.0  0.0
  0.447214  0.0  0.0   0.0  0.894427
 -0.0       1.0  0.0  -0.0  0.0
  0.0       0.0  0.0   1.0  0.0

In [168]:
u == F.U && s == F.S && v == F.V

true

**GeneralizedSVD**

GeneralizedSVD <: Factorization

* GeneralizedSVD 타입은 두 개의 행렬을 입력받아 반환하는 SVD 타입으로 ```A = F.U*F.D1*F.R0*F.Q'``` 와 ```B = F.V*F.D2*F.R0*F.Q'```로 분해되면서 SVD 타입으로 반환된다.

    * M by N 행렬 ```A``` 와 P by N 행렬 ```B``` 일 때, 분해되는 결과는 아래와 같다. 



    

| matrix | descriptiion |
|:-------:|:-------------:|
|```U``` | M-by-M orthogonal matrix|
|```V``` | P-by-P orthogonal matrix|
|```Q``` | N-by-N orthogonal matrix|
|```D1``` | M-by-(K+L) diagonal matrix with 1s in the first K entries |
|```D2``` | P-by-(K+L) matrix whose top right L-by-L block is diagonal |
|```R0``` | (K+L)-by-N matrix whose rightmost (K+L)-by-(K+L) block is nonsingular upper block triangular |
| *K+L is the effective numerical rank of the matrix [A; B] |



In [169]:
A = [1. 0.; 0. -1.]

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [170]:
B = [0. 1.; 1. 0.]

2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0

In [171]:
F = svd(A, B)

GeneralizedSVD{Float64, Matrix{Float64}, Float64, Vector{Float64}}
U factor:
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
V factor:
2×2 Matrix{Float64}:
 -0.0  -1.0
  1.0   0.0
Q factor:
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
D1 factor:
2×2 Matrix{Float64}:
 0.707107  0.0
 0.0       0.707107
D2 factor:
2×2 Matrix{Float64}:
 0.707107  0.0
 0.0       0.707107
R0 factor:
2×2 Matrix{Float64}:
 1.41421   0.0
 0.0      -1.41421

In [172]:
F.U*F.D1*F.R0*F.Q'

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [173]:
F.V*F.D2*F.R0*F.Q'

2×2 Matrix{Float64}:
 -0.0  1.0
  1.0  0.0

**function**

* SVD 함수는 특이값 분해 결과를 리턴하는 함수로 F::SVD 객체의 F.U, F.S, F.V, F.Vt 필드로 추출한다.
 
    * ```A = U * Diagonal(S) * Vt``` 

    * 줄리아의 SVD 함수는 ```V```를 추출하는 것 보다 더 효율적인 ```Vt```를 추출한다. 
    
    * 인자 중 full은 ```full = false```가 기본값으로 "thin" SVD 결과가 반환된다. 예를 들어 full factorization의 결과로 M by M의 ```V```와 N by N의 ```U```가 반환된다면, thin factorization ```U```로 M by K, ```V```로 N by k 로 반환된다. 여기서 k의 값은 min(M, N) 으로 결정된다.

In [174]:
# svd(A; full::Bool = false, alg::Algorithm = default_svd_alg(A)) -> SVD

A = rand(4,3)

4×3 Matrix{Float64}:
 0.497105   0.646134  0.992762
 0.896949   0.664355  0.066382
 0.714676   0.461985  0.340796
 0.0141409  0.100195  0.867636

In [175]:
F = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×3 Matrix{Float64}:
 -0.660698   0.34222    0.598298
 -0.497329  -0.624785   0.102897
 -0.468866  -0.252842  -0.645274
 -0.310335   0.654676  -0.463761
singular values:
3-element Vector{Float64}:
 1.8710624951685035
 0.9920847665925455
 0.13685083687468455
Vt factor:
3×3 Matrix{Float64}:
 -0.595378  -0.537131  -0.597508
 -0.566205  -0.24713    0.786345
 -0.570032   0.806485  -0.156991

In [176]:
A ≈ F.U * Diagonal(F.S) * F.Vt

true

In [177]:
U, S, V = F

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×3 Matrix{Float64}:
 -0.660698   0.34222    0.598298
 -0.497329  -0.624785   0.102897
 -0.468866  -0.252842  -0.645274
 -0.310335   0.654676  -0.463761
singular values:
3-element Vector{Float64}:
 1.8710624951685035
 0.9920847665925455
 0.13685083687468455
Vt factor:
3×3 Matrix{Float64}:
 -0.595378  -0.537131  -0.597508
 -0.566205  -0.24713    0.786345
 -0.570032   0.806485  -0.156991

In [178]:
A ≈ U * Diagonal(S) * V'

true

In [179]:
Uonly, = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×3 Matrix{Float64}:
 -0.660698   0.34222    0.598298
 -0.497329  -0.624785   0.102897
 -0.468866  -0.252842  -0.645274
 -0.310335   0.654676  -0.463761
singular values:
3-element Vector{Float64}:
 1.8710624951685035
 0.9920847665925455
 0.13685083687468455
Vt factor:
3×3 Matrix{Float64}:
 -0.595378  -0.537131  -0.597508
 -0.566205  -0.24713    0.786345
 -0.570032   0.806485  -0.156991

In [180]:
Uonly == U

true

* SVD 함수는 두 개의 행렬이 입력으로 들어오면 ```[A;B] = [F.U * F.D1; F.V * F.D2] * F.R0 * F.Q'``` 에 해당하는 GeneralizedSVD를 계산한다.

* factorization object F : ```[A;B] = [F.U * F.D1; F.V * F.D2] * F.R0 * F.Q'```

* M by N 행렬 ```A``` 와 P by N 행렬 ```B``` 일 때, 분해되는 결과는 아래와 같다
    
| matrix | descriptiion |
|:-------:|:-------------:|
|```U``` | M-by-M orthogonal matrix|
|```V``` | P-by-P orthogonal matrix|
|```Q``` | N-by-N orthogonal matrix|
|```D1``` | M-by-(K+L) diagonal matrix with 1s in the first K entries |
|```D2``` | P-by-(K+L) matrix whose top right L-by-L block is diagonal |
|```R0``` | (K+L)-by-N matrix whose rightmost (K+L)-by-(K+L) block is nonsingular upper block triangular |
| *K+L is the effective numerical rank of the matrix [A; B] |

* GeneralizedSVD는 **인간 대 효모 게놈**, **신호 대 잡음**, **클러스터 간** 또는 **클러스터 내**에서 A에 얼마나 속하는지 비교하고 싶을 때 사용된다.

In [181]:
# svd(A, B) -> GeneralizedSVD
A = randn(3,2); B=randn(4,2)

4×2 Matrix{Float64}:
 -0.631577   0.622602
  0.721437   0.0290324
 -0.701443  -0.118416
 -1.30986   -2.14966

In [182]:
F = svd(A, B)

GeneralizedSVD{Float64, Matrix{Float64}, Float64, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.864641   -0.369824  0.340037
  0.501985   -0.663133  0.555218
  0.0201572   0.650758  0.759018
V factor:
4×4 Matrix{Float64}:
 -0.168541   -0.727673   -0.17852    0.640481
 -0.0920944   0.510701    0.497967   0.694789
  0.12422    -0.457497    0.84368   -0.251933
  0.97349    -0.0192909  -0.091454   0.208763
Q factor:
2×2 Matrix{Float64}:
 0.28008    0.959977
 0.959977  -0.28008
D1 factor:
3×2 Matrix{Float64}:
 0.203215  0.0
 0.0       0.549956
 0.0       0.0
D2 factor:
4×2 Matrix{Float64}:
 0.979134  0.0
 0.0       0.835193
 0.0       0.0
 0.0       0.0
R0 factor:
2×2 Matrix{Float64}:
 -2.54988  -0.662795
  0.0       1.46451

In [183]:
U,V,Q,C,S,R = F

GeneralizedSVD{Float64, Matrix{Float64}, Float64, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.864641   -0.369824  0.340037
  0.501985   -0.663133  0.555218
  0.0201572   0.650758  0.759018
V factor:
4×4 Matrix{Float64}:
 -0.168541   -0.727673   -0.17852    0.640481
 -0.0920944   0.510701    0.497967   0.694789
  0.12422    -0.457497    0.84368   -0.251933
  0.97349    -0.0192909  -0.091454   0.208763
Q factor:
2×2 Matrix{Float64}:
 0.28008    0.959977
 0.959977  -0.28008
D1 factor:
3×2 Matrix{Float64}:
 0.203215  0.0
 0.0       0.549956
 0.0       0.0
D2 factor:
4×2 Matrix{Float64}:
 0.979134  0.0
 0.0       0.835193
 0.0       0.0
 0.0       0.0
R0 factor:
2×2 Matrix{Float64}:
 -2.54988  -0.662795
  0.0       1.46451

In [184]:
H = R*Q'

2×2 Matrix{Float64}:
 -1.35044  -2.26219
  1.4059   -0.41018

In [185]:
[A; B] ≈ [U*C; V*S]*H

true

In [186]:
[A; B] ≈ [F.U*F.D1; F.V*F.D2]*F.R0*F.Q'

true

In [187]:
Uonly, = svd(A,B)

GeneralizedSVD{Float64, Matrix{Float64}, Float64, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.864641   -0.369824  0.340037
  0.501985   -0.663133  0.555218
  0.0201572   0.650758  0.759018
V factor:
4×4 Matrix{Float64}:
 -0.168541   -0.727673   -0.17852    0.640481
 -0.0920944   0.510701    0.497967   0.694789
  0.12422    -0.457497    0.84368   -0.251933
  0.97349    -0.0192909  -0.091454   0.208763
Q factor:
2×2 Matrix{Float64}:
 0.28008    0.959977
 0.959977  -0.28008
D1 factor:
3×2 Matrix{Float64}:
 0.203215  0.0
 0.0       0.549956
 0.0       0.0
D2 factor:
4×2 Matrix{Float64}:
 0.979134  0.0
 0.0       0.835193
 0.0       0.0
 0.0       0.0
R0 factor:
2×2 Matrix{Float64}:
 -2.54988  -0.662795
  0.0       1.46451

In [188]:
U == Uonly

true

#### 2.10.2 svdvals

* A의 특이값(singular value)을 내림차순으로 반환해 주는 함수

In [189]:
# svdvals(A)
A = [1. 0. 0. 0. 2.; 0. 0. 3. 0. 0.; 0. 0. 0. 0. 0.; 0. 2. 0. 0. 0.]

4×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  2.0
 0.0  0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0  0.0

In [190]:
svdvals(A)

4-element Vector{Float64}:
 3.0
 2.23606797749979
 2.0
 0.0

Return the generalized singular values from the generalized singular value decomposition of A and B. See also svd.

In [191]:
A = [1. 0.; 0. -1.]

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [192]:
B = [0. 1.; 1. 0.]

2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0

In [193]:
svdvals(A, B)

2-element Vector{Float64}:
 1.0
 1.0

### 2.11 Schur

**type**

Schur <: Factorization

* 슈어 분해는 임의의 복소수 정사각 행렬을 이와 유니터리 닮음인 상삼각 행렬로 나타내는 행렬 분해로 ```A = F.vectors * F.Schur * F.vectors'```와 같이 표현되며 이와 같은 분해 결과를 객체로 타입을 Schur 타입이라 한다.

    * F.vectors or F.Z
    
    * F.Schur or F.T
    

* A의 고유값(eigenvalues)은 ```F.values```를 통해 얻을 수 있다. 

In [194]:
A = [5. 7.; -2. -4.]

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [195]:
F = schur(A)

Schur{Float64, Matrix{Float64}, Vector{Float64}}
T factor:
2×2 Matrix{Float64}:
 3.0   9.0
 0.0  -2.0
Z factor:
2×2 Matrix{Float64}:
  0.961524  0.274721
 -0.274721  0.961524
eigenvalues:
2-element Vector{Float64}:
  3.0
 -2.0

In [196]:
F.vectors * F.Schur * F.vectors'

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [197]:
t, z, vals = F

Schur{Float64, Matrix{Float64}, Vector{Float64}}
T factor:
2×2 Matrix{Float64}:
 3.0   9.0
 0.0  -2.0
Z factor:
2×2 Matrix{Float64}:
  0.961524  0.274721
 -0.274721  0.961524
eigenvalues:
2-element Vector{Float64}:
  3.0
 -2.0

In [198]:
t == F.T && z == F.Z && vals == F.values

true

**generalizedSchur**

GeneralizedSchur <: Factorization

* 두 개의 행렬이 인수로 들어올 때 반환하는 Schur 분해 타입이다. 

> If F::GeneralizedSchur is the factorization object, the (quasi) triangular Schur factors can be obtained via ```F.S``` and ```F.T```, the left unitary/orthogonal Schur vectors via ```F.left``` or ```F.Q```, and the right unitary/orthogonal Schur vectors can be obtained with ```F.right``` or ```F.Z``` such that ```A = F.left*F.S*F.right'``` and ```B=F.left*F.T*F.right'```. 


>  The generalized eigenvalues of A and B can be obtained with F.α./F.β.


> Iterating the decomposition produces the components F.S, F.T, F.Q, F.Z, F.α, and F.β.

**function**

schur(A) -> F::Schur

* Schur 함수는 Schur 분해를 수행하는 함수로 ```A = F.vectors * F.Schur * F.vectors'``` 의 결과를 반환한다.

In [199]:
A = [5. 7.; -2. -4.]

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [200]:
 F = schur(A)

Schur{Float64, Matrix{Float64}, Vector{Float64}}
T factor:
2×2 Matrix{Float64}:
 3.0   9.0
 0.0  -2.0
Z factor:
2×2 Matrix{Float64}:
  0.961524  0.274721
 -0.274721  0.961524
eigenvalues:
2-element Vector{Float64}:
  3.0
 -2.0

In [201]:
 F.vectors * F.Schur * F.vectors'

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [202]:
t, z, vals = F

Schur{Float64, Matrix{Float64}, Vector{Float64}}
T factor:
2×2 Matrix{Float64}:
 3.0   9.0
 0.0  -2.0
Z factor:
2×2 Matrix{Float64}:
  0.961524  0.274721
 -0.274721  0.961524
eigenvalues:
2-element Vector{Float64}:
  3.0
 -2.0

In [203]:
t == F.T && z == F.Z && vals == F.values

true

**Schur!**

입력하는 인수인 A에 오버래핑을 실시하는 함수

In [204]:
# schur!(A::StridedMatrix) -> F::Schur
A = [5. 7.; -2. -4.]

2×2 Matrix{Float64}:
  5.0   7.0
 -2.0  -4.0

In [205]:
F = schur!(A)

Schur{Float64, Matrix{Float64}, Vector{Float64}}
T factor:
2×2 Matrix{Float64}:
 3.0   9.0
 0.0  -2.0
Z factor:
2×2 Matrix{Float64}:
  0.961524  0.274721
 -0.274721  0.961524
eigenvalues:
2-element Vector{Float64}:
  3.0
 -2.0

In [206]:
A

2×2 Matrix{Float64}:
 3.0   9.0
 0.0  -2.0