# Linear Algebra.jl

## 2. Special matrices

* 다양한 대칭성과 구조를 가진 행렬들은 다양한 행렬 분해법과 선형대수 전반에 연관되어 나타난다. 줄리아는 빠른 계산을 위해 특별한 행렬 구조를 타입화하여 행렬 계산에 이용한다.

* 아래는 줄리아에서 사용되는 행렬 구조 타입이며 LAPACK  에서 정의된 각 행렬 타입별 최적화 연산을 사용가능 한지 확인하고 이를 지원한다.

    - _LAPACK: Linear Algebra Package: 선형대수 연산을 수행하기 위해 널리 사용되는 포트란 작성 패키지_


> 줄리아에서 제공하는 행렬 구조 타입과 기본 연산 및 최적화 방식을 지원하는 함수 종류에 관한 표

|	Type 	|	Description	|	```+```	|	```-```	|	```*```	|	```\```	|	Other functions with optimized methods
|	:-----	|	:------------	|	:------------	|	:------------	|	:------------	|	:------------	|	:------------
|	**Symmetric**	|	Symmetric matrix	|		|		|		|	MV	|	```inv```, ```sqrt```, ```exp```
|	**Hermitian**	|	Hermitian matrix	|		|		|		|	MV	|	```inv```, ```sqrt```, ```exp```
|	**UpperTriangular**	|	Upper triangular matrix	|		|		|	MV	|	MV	|	```inv```, ```det```
|	**UnitUpperTriangular**	|	Upper triangular matrix with unit diagonal	|		|		|	MV	|	MV	|	```inv```, ```det```
|	**LowerTriangular**	|	Lower triangular matrix	|		|		|	MV	|	MV	|	```inv```, ```det```
|	**UnitLowerTriangular**	|	Lower triangular matrix with unit diagonal	|		|		|	MV	|	MV	|	```inv```, ```det```
|	**UpperHessenberg**	|	Upper Hessenberg matrix	|		|		|		|	MV	|	```inv```, ```det```
|	**Tridiagonal**	|	Tridiagonal matrix	|	M	|	M	|	MS	|	MV	|	
|	**SymTridiagonal**	|	Symmetric tridiagonal matrix	|	M	|	M	|	MS	|	MV	|	```eigmax```, ```eigmin```
|	**Bidiagonal**	|	Upper/lower bidiagonal matrix	|	M	|	M	|	MS	|	MV	|	
|	**Diagonal**	|	Diagonal matrix	|	M	|	M	|	MV	|	MV	|	```inv```, ```det```, ```logdet```, ```/```
|	**UniformScaling**	|	Uniform scaling operator	|	M	|	M	|	MVS	|	MVS	|	```/```


**Legend:**

* M (matrix): An optimized method for matrix-matrix operations is available
* V (vector): An optimized method for matrix-vector operations is available
* S (scalar): An optimized method for matrix-scalar operations is available

* 이해를 돕기 위해 아래와 같이 시각화 함

![image1.png](drawing/metrices1.png)

![image2.png](drawing/metrices2.png)

### 2.1 Symmetric type

* **Symmetric 함수**를 이용하여 일반 행렬을 대칭 행렬로 변환하고 그 타입을 Symmetric으로 지정함

* Symmetric 함수는 상삼각행렬을 기준으로 대칭 행렬을 만드는 것이 기본 값(```uplo = :U```)이며, 만약 하삼각행렬을 기준으로 대칭 행렬을 만들고자 한다면 ```uplo = :L``` 인자를 넣어서 하삼각행렬을 기준으로 생성되는 대칭 행렬을 만들 수 있다.

* A 행렬이 대칭 행렬이 아닌 경우 인수에 ```:U```를 넣은 결과와 ```:L```를 넣은 결과가 상이한 점에 주의!

In [1]:
using Pkg
using LinearAlgebra

A = [1 0 2 0 3; 0 4 0 5 0; 6 0 7 0 8; 0 9 0 1 0; 2 0 3 0 4]

5×5 Matrix{Int64}:
 1  0  2  0  3
 0  4  0  5  0
 6  0  7  0  8
 0  9  0  1  0
 2  0  3  0  4

In [2]:
Supper = Symmetric(A)

5×5 Symmetric{Int64, Matrix{Int64}}:
 1  0  2  0  3
 0  4  0  5  0
 2  0  7  0  8
 0  5  0  1  0
 3  0  8  0  4

In [3]:
Slower = Symmetric(A, :L)

5×5 Symmetric{Int64, Matrix{Int64}}:
 1  0  6  0  2
 0  4  0  9  0
 6  0  7  0  3
 0  9  0  1  0
 2  0  3  0  4

### 2.2 Hermitian type

* 에르미트 행렬은 켤레 복소수로 대칭되는 대칭 행렬이다. 

* 에르미트 행렬 역시 상삼각행렬을 기준으로 대칭행렬을 만드는 것이 기본값이며(```uplo = :U```), 만약 하삼각행렬을 기준으로 대칭 행렬을 만들고자 한다면 ```uplo = :L``` 인자를 넣어서 하삼각행렬을 기준으로 생성되는 대칭 행렬을 만들 수 있다.

In [4]:
A = [1 0 2+2im 0 3-3im; 0 4 0 5 0; 6-6im 0 7 0 8+8im; 0 9 0 1 0; 2+2im 0 3-3im 0 4]

5×5 Matrix{Complex{Int64}}:
 1+0im  0+0im  2+2im  0+0im  3-3im
 0+0im  4+0im  0+0im  5+0im  0+0im
 6-6im  0+0im  7+0im  0+0im  8+8im
 0+0im  9+0im  0+0im  1+0im  0+0im
 2+2im  0+0im  3-3im  0+0im  4+0im

In [5]:
Hupper = Hermitian(A)

5×5 Hermitian{Complex{Int64}, Matrix{Complex{Int64}}}:
 1+0im  0+0im  2+2im  0+0im  3-3im
 0+0im  4+0im  0+0im  5+0im  0+0im
 2-2im  0+0im  7+0im  0+0im  8+8im
 0+0im  5+0im  0+0im  1+0im  0+0im
 3+3im  0+0im  8-8im  0+0im  4+0im

In [6]:
Hlower = Hermitian(A, :L)

5×5 Hermitian{Complex{Int64}, Matrix{Complex{Int64}}}:
 1+0im  0+0im  6+6im  0+0im  2-2im
 0+0im  4+0im  0+0im  9+0im  0+0im
 6-6im  0+0im  7+0im  0+0im  3+3im
 0+0im  9+0im  0+0im  1+0im  0+0im
 2+2im  0+0im  3-3im  0+0im  4+0im

### 2.3 Upper Triangular type

- ```UpperTriangular``` 함수를 이용하면 주 대각 원소 아래쪽에 있는 모든 원소가 0인 상 삼각 행렬 타입으로 변환할 수 있다. 

In [7]:
A = [1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0]

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [8]:
UpperTriangular(A)

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  2.0  3.0
  ⋅   5.0  6.0
  ⋅    ⋅   9.0

### 2.4 Unit Upper Triangular type

* ```UnitUpperTriangular``` 함수를 이용하면 주 대각 원소를 unit 값인 1로 치환하고 주 대각 원소 아래쪽 원소가 모두 0인 상 삼각 행렬로 변환할 수 있다.

In [9]:
A = [1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0]

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [10]:
UnitUpperTriangular(A)

3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  2.0  3.0
  ⋅   1.0  6.0
  ⋅    ⋅   1.0

### 2.5 Lower Triangular type

* ```LowerTriangular``` 함수를 이용하면 주 대각 원소 위쪽에 있는 모든 원소가 0인 하 삼각 행렬(lower triangular matrix)을 구할 수 있다.

In [11]:
A = [1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0]

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [12]:
LowerTriangular(A)

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 1.0   ⋅    ⋅ 
 4.0  5.0   ⋅ 
 7.0  8.0  9.0

### 2.6 Unit Lower Triangular type

* ```UnitLowerTriangular``` 함수를 이용하면 주 대각 원소를 unit 값인 1로 치환하고 주 대각 원소 위 쪽 원소가 모두 0인 하삼각행렬(lower triangular matrix)로 변환할 수 있다.

In [13]:
A = [1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0]

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [14]:
UnitLowerTriangular(A)

3×3 UnitLowerTriangular{Float64, Matrix{Float64}}:
 1.0   ⋅    ⋅ 
 4.0  1.0   ⋅ 
 7.0  8.0  1.0

### 2.7 UpperHessenberg

* 헤센버그 행렬은 주 대각 원소의 첫 번째 아래 대각 원소를 제외하고 나머지 아래쪽 원소들이 모두 0인 행렬을 말한다.

* 다시 말해 주 대각 원소와 그 아래 대각 원소를 제외하고는 원소값이 무시되는 행렬로 다음과 같은 형태라고 볼 수 있다.

    - (원문) _Entries of A below the first subdiagonal are ignored._

**((상)헤센버그 행렬 예시)**
$$\begin{matrix}
1 & 2 & 3 & 4 & 5 & 6\\
1 & 2 & 3 & 4 & 5 & 6\\
\cdot & 2 & 3 & 4 & 5 & 6\\
\cdot & \cdot & 3 & 4 & 5 & 6\\
\cdot & \cdot & \cdot & 4 & 5 & 6\\
\cdot & \cdot & \cdot & \cdot & 5 & 6\\
\end{matrix}$$


In [15]:
A = [1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]

4×4 Matrix{Int64}:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

In [16]:
UpperHessenberg(A)

4×4 UpperHessenberg{Int64, Matrix{Int64}}:
 1   2   3   4
 5   6   7   8
 ⋅  10  11  12
 ⋅   ⋅  15  16

### 2.8 Tridiagonal type

* ```Tridiagonal``` 함수를 이용하면 대각선의 성분과 대각선에 이웃하는 원소 이외의 다른 성분들의 값이 모두 0인 삼중대각행렬을 만들 수 있다.

* Construct a tridiagonal matrix from the first subdiagonal, diagonal, and first superdiagonal, respectively.

In [17]:
dl = [1, 2, 3]
du = [4, 5, 6]
d = [7, 8, 9, 0]

4-element Vector{Int64}:
 7
 8
 9
 0

In [18]:
Tridiagonal(dl, d, du)

4×4 Tridiagonal{Int64, Vector{Int64}}:
 7  4  ⋅  ⋅
 1  8  5  ⋅
 ⋅  2  9  6
 ⋅  ⋅  3  0

In [19]:
A = [1 2 3 4; 1 2 3 4; 1 2 3 4; 1 2 3 4]

4×4 Matrix{Int64}:
 1  2  3  4
 1  2  3  4
 1  2  3  4
 1  2  3  4

In [20]:
Tridiagonal(A)

4×4 Tridiagonal{Int64, Vector{Int64}}:
 1  2  ⋅  ⋅
 1  2  3  ⋅
 ⋅  2  3  4
 ⋅  ⋅  3  4

### 2.9 SymTridiagonal type

* ```SymTridiagonal``` 함수를 이용하면 대각선에 이웃하는 원소가 대칭인 삼중대각행렬을 만들 수 있다. 

* Construct a symmetric tridiagonal matrix from the diagonal **(dv)** and first sub/super-diagonal **(ev)**, respectively. 

**(예시 1)**

In [21]:
dv = [1, 2, 3, 4]
ev = [7, 8, 9]
SymTridiagonal(dv, ev)

4×4 SymTridiagonal{Int64, Vector{Int64}}:
 1  7  ⋅  ⋅
 7  2  8  ⋅
 ⋅  8  3  9
 ⋅  ⋅  9  4

**(예시 2)**

* 특히 ```SymTridiagonal``` 함수를 이용하면 하나의 행렬이 블록이 되어 또 다른 행렬의 원소로 들어가는 행렬을 생성할 때 대칭인 삼중 대각행렬을 만들 수 있다.

    * 이때, 대각 원소(dv)로 들어가는 블록 행렬은 블록 자체가 대칭 행렬이 되도록 변환(기준은 upper)되며,
    
    * 상초대각 원소(superdiagonal, 대각원소 첫번째 위쪽에 있는 원소)로 들어가는 블록 행렬을 기준으로 하초대각 원소(subdiagonal, 대각원소 첫번째 아래쪽에 있는 원소)가 생성되며, 상초대각원소와 대칭이 되도록 하초대각 원소가 (상초대각원소 행렬의 전치 행렬로) 변환된다.

    *_For SymTridiagonal block matrices, the elements of dv are symmetrized. The argument ev is interpreted as the superdiagonal. Blocks from the subdiagonal are (materialized) transpose of the corresponding superdiagonal blocks._

* 대각 원소 행렬  $dv = \left\{\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}\right\}$


* 초대각원소(sub/super-diagonal) 행렬 $dv = \left\{\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}\right\}$

* SymTridiagonal 함수 적용 전 -> 후 

$$\begin{pmatrix}
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  & 0  \\
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  \\
0 & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  \\
\end{pmatrix} \Rightarrow \begin{pmatrix}
\begin{pmatrix}
1 & 2 \\
2 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  & 0  \\
\begin{pmatrix}
1 & 3 \\
2 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
2 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}  \\
0 & \begin{pmatrix}
1 & 3 \\
2 & 4 \\
\end{pmatrix}  & \begin{pmatrix}
1 & 2 \\
2 & 4 \\
\end{pmatrix}  \\
\end{pmatrix} $$

In [22]:
# block metices 예제
A = SymTridiagonal(fill([1 2; 3 4], 3), fill([1 2; 3 4], 2));

In [23]:
println(fill([1 2; 3 4], 3))
println(fill([1 2; 3 4], 2))

[[1 2; 3 4], [1 2; 3 4], [1 2; 3 4]]
[[1 2; 3 4], [1 2; 3 4]]


In [24]:
# 생성한 삼중대각행렬의 형태 확인
println("삼중대각행렬의 차원은 몇 개? ", ndims(A))
println("삼중대각행렬의 dimension은? ", size(A))
println("삼중대각행렬의 축은? ", axes(A))

삼중대각행렬의 차원은 몇 개? 2
삼중대각행렬의 dimension은? (3, 3)
삼중대각행렬의 축은? (Base.OneTo(3), Base.OneTo(3))


In [25]:
# 3 by 3 행렬인 A의 원소들 형태 확인
A[1,1]

2×2 Symmetric{Int64, Matrix{Int64}}:
 1  2
 2  4

In [26]:
A[1,2]

2×2 Matrix{Int64}:
 1  2
 3  4

In [27]:
A[1,3] # zero 지점 항목이기 때문에 error 발생

LoadError: MethodError: no method matching zero(::Type{Matrix{Int64}})
Closest candidates are:
  zero(::Union{Type{P}, P}) where P<:Dates.Period at C:\Users\jeffr\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\periods.jl:53
  zero(::UniformScaling{T}) where T at C:\Users\jeffr\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\LinearAlgebra\src\uniformscaling.jl:135
  zero(::SparseArrays.AbstractSparseArray) at C:\Users\jeffr\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\SparseArrays\src\SparseArrays.jl:42
  ...

In [28]:
A[2,1]

2×2 Matrix{Int64}:
 1  3
 2  4

In [29]:
A[2,2]

2×2 Symmetric{Int64, Matrix{Int64}}:
 1  2
 2  4

In [30]:
A[2,3]

2×2 Matrix{Int64}:
 1  2
 3  4

In [31]:
A[3,1] # zero 지점 항목이기 때문에 error 발생

LoadError: MethodError: no method matching zero(::Type{Matrix{Int64}})
Closest candidates are:
  zero(::Union{Type{P}, P}) where P<:Dates.Period at C:\Users\jeffr\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\periods.jl:53
  zero(::UniformScaling{T}) where T at C:\Users\jeffr\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\LinearAlgebra\src\uniformscaling.jl:135
  zero(::SparseArrays.AbstractSparseArray) at C:\Users\jeffr\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\SparseArrays\src\SparseArrays.jl:42
  ...

In [32]:
A[3,2]

2×2 Matrix{Int64}:
 1  3
 2  4

In [33]:
A[3,3]

2×2 Symmetric{Int64, Matrix{Int64}}:
 1  2
 2  4

**(예시 3)**

* 또한, 대칭 행렬 A로부터 대칭삼중대각행렬(symmetric tridiagonal matrix)을 만들 수 있다. 

- _Construct a symmetric tridiagonal matrix from the diagonal and first superdiagonal of the symmetric matrix A._

In [34]:
A = [1 2 3; 2 4 5; 3 5 6]

3×3 Matrix{Int64}:
 1  2  3
 2  4  5
 3  5  6

In [35]:
SymTridiagonal(A)

3×3 SymTridiagonal{Int64, Vector{Int64}}:
 1  2  ⋅
 2  4  5
 ⋅  5  6

In [36]:
B = reshape([[1 2; 2 3], [1 2; 3 4], [1 3; 2 4], [1 2; 2 3]], 2, 2);
B

2×2 Matrix{Matrix{Int64}}:
 [1 2; 2 3]  [1 3; 2 4]
 [1 2; 3 4]  [1 2; 2 3]

In [37]:
SymTridiagonal(B)

2×2 SymTridiagonal{Matrix{Int64}, Vector{Matrix{Int64}}}:
 [1 2; 2 3]  [1 3; 2 4]
 [1 2; 3 4]  [1 2; 2 3]

* **(case A)** 3×3 Matrix{Int64}: 에서 3×3 SymTridiagonal{Int64, Vector{Int64}}:로 변환된 것을 확인할 수 있다. 

* **(case B)** 2×2 Matrix{Matrix{Int64}}: 에서 2×2 SymTridiagonal{Matrix{Int64}, Vector{Matrix{Int64}}}: 로 변환된 것을 확인할 수 있다.

### 2.10 Bidiagonal type

* ```Bidiagonal``` 함수를 이용하면 이중대각행렬을 만들 수 있다. 이때 ```:U```인자를 사용하면 **상이중대각행렬(upper bidiagonal matrix)**, ```:L``` 인자를 이용하면 **하이중대각행렬(lower bidiagonal matrix)** 을 만들 수 있다. 

* _Constructs an upper (uplo=:U) or lower (uplo=:L) bidiagonal matrix using the given diagonal (dv) and off-diagonal (ev) vectors. The result is of type Bidiagonal and provides efficient specialized linear solvers, but may be converted into a regular matrix with convert(Array, _) (or Array(_) for short). The length of ev must be one less than the length of dv._

In [38]:
# 대각 원소 지정
dv = [1, 2, 3, 4];

# 초대각 원소 지정
ev = [7, 8, 9];

In [39]:
Bu = Bidiagonal(dv, ev, :U) # ev is on the first superdiagonal

4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  7  ⋅  ⋅
 ⋅  2  8  ⋅
 ⋅  ⋅  3  9
 ⋅  ⋅  ⋅  4

In [40]:
Bl = Bidiagonal(dv, ev, :L) # ev is on the first subdiagonal

4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 7  2  ⋅  ⋅
 ⋅  8  3  ⋅
 ⋅  ⋅  9  4

In [41]:
A = [1 1 1 1; 2 2 2 2; 3 3 3 3; 4 4 4 4];
Bidiagonal(A, :U)

4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  1  ⋅  ⋅
 ⋅  2  2  ⋅
 ⋅  ⋅  3  3
 ⋅  ⋅  ⋅  4

In [42]:
Bidiagonal(A, :L)

4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 2  2  ⋅  ⋅
 ⋅  3  3  ⋅
 ⋅  ⋅  4  4

### 2.11 Diagonal type

* ```diagonal``` 함수를 이용하면 주 대각 원소가 아닌 원소가 0인 대각 행렬을 만들 수 있다. 


In [43]:
Diagonal([1, 10, 100])

3×3 Diagonal{Int64, Vector{Int64}}:
 1   ⋅    ⋅
 ⋅  10    ⋅
 ⋅   ⋅  100

In [44]:
diagm([7, 13])

2×2 Matrix{Int64}:
 7   0
 0  13

In [45]:
A = permutedims(reshape(1:15, 5, 3))

3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [46]:
Diagonal(A)

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅   ⋅
 ⋅  7   ⋅
 ⋅  ⋅  13

In [47]:
diag(A, 0)

3-element Vector{Int64}:
  1
  7
 13

In [48]:
diag(A, 1)

3-element Vector{Int64}:
  2
  8
 14

In [49]:
diag(A, 2)

3-element Vector{Int64}:
  3
  9
 15

### 2.12 UniformScaling type

* ```UniformScaling``` 함수를 이용하면 인수로 입력하는 값과 단위 행렬을 곱하여 스케일링된 단위 행렬을 구할 수 있다. $\lambda \times I$

* **단위 행렬(identity matrix)** $I$(An object of type UniformScaling)도 이 행렬 타입에 속한다.

* _Generically sized uniform scaling operator defined as a scalar times the identity operator, λ*I. Although without an explicit size, it acts similarly to a matrix in many cases and includes support for some indexing. See also I._

In [50]:
J = UniformScaling(2.)

UniformScaling{Float64}
2.0*I

In [51]:
A = [1. 2.; 3. 4.]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [52]:
J*A # J와 A의 행렬곱

2×2 Matrix{Float64}:
 2.0  4.0
 6.0  8.0

In [53]:
J[1:2, 1:2]

2×2 Matrix{Float64}:
 2.0  0.0
 0.0  2.0